/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

import javax.swing.*;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;

/**
 *
 * @author saray
 */
public class UserView extends javax.swing.JFrame {

    private User user;
    /**
     * Creates new form UserView
     */
    public UserView(User user) {
        // Instantiate list models
        followingListModel = new DefaultListModel<>();
        newsFeedListModel = new DefaultListModel<>();
        this.user = user;
        treeView = Window.getInstance().getTree();

        // Initialize components;
        initComponents();
    
        // Now set the models for the JLists
        jList1.setModel(followingListModel);
        jList2.setModel(newsFeedListModel);
        // Attach event listeners to buttons
        jButton1.addActionListener(new ActionListener() 
        {
            @Override
            public void actionPerformed(ActionEvent e) 
            {
                postTweet(user);
            }
        });
    
        jButton2.addActionListener(new ActionListener() 
        {
            @Override
            public void actionPerformed(ActionEvent e) 
            {
                followUser();
            }
        });
    }
    
   
    private void postTweet(User user)
     { //handles the UI part of the posting process
        if(!jTextArea2.getText().isEmpty())
        {
            String tweet = user.getUserID() + " posted: " + jTextArea2.getText();
            newsFeedListModel.addElement(tweet);
            jList2.setModel(newsFeedListModel);
            user.post(tweet); //calls user post method
            jTextArea2.setText("");
        }
    }

    private void followUser() //Test version, to help find issue with original follow user 
    {
        String userID = jTextArea1.getText().trim(); // Get the user ID from the text area
        User userToFollow = treeView.findUser(userID); // Assuming treeView can find a User by ID
    
        if (userToFollow != null) 
        {
            user.follow(userToFollow); // 'user' is the current User object of this UserView
        }
         else 
        {
            JOptionPane.showMessageDialog(this, "User not found: " + userID);
        }
    }
    
///////////////////////////////////////////////////////////////////////////////////////////// Under constrution
    // Method to handle following a new user, Redoing th
/*private void followUser() {
         //Will follow the user and use the Observer Method

    String userID = jTextArea1.getText(); //.trim(); //Trim to remove any whitespace
    if (!userID.isEmpty() && !followingListModel.contains(userID)) {
        followingListModel.addElement(userID);
        jList1.setModel(followingListModel);
        jTextArea1.setText(""); // Clear the text area after adding
        System.out.println("It adds the user to the following list");

        user.follow((Observer)treeView.findUser(userID));    //Issue is also here it looks like its null
    }// THE ISSUE IS HERE!!!!!!!
}
*/
/////////////////////////////////////////////////////////////////////////////////////////
    public void receive(String str) 
    {
        SwingUtilities.invokeLater(() -> {
        newsFeedListModel.addElement(str);
        jList2.setModel(newsFeedListModel);
        System.out.println(user.getDisplayName()+ " User Interface | Time Created: "+user.getTime());
        System.out.println("its working");
    });
}




    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jSplitPane1 = new javax.swing.JSplitPane();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        jButton2 = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        jList1 = new javax.swing.JList<>();
        jSplitPane2 = new javax.swing.JSplitPane();
        jScrollPane3 = new javax.swing.JScrollPane();
        jTextArea2 = new javax.swing.JTextArea();
        jButton1 = new javax.swing.JButton();
        jScrollPane4 = new javax.swing.JScrollPane();
        jList2 = new javax.swing.JList<>();

      

        jSplitPane1.setDividerLocation(150);

        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        jTextArea1.setToolTipText("User ID");
        jScrollPane1.setViewportView(jTextArea1);

        jSplitPane1.setLeftComponent(jScrollPane1);

        jButton2.setText("Follow User");
        jSplitPane1.setRightComponent(jButton2);

        jList1.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        jList1.setToolTipText("Current Following");
        jScrollPane2.setViewportView(jList1);

        jSplitPane2.setDividerLocation(150);

        jScrollPane3.setToolTipText("Tweet Message");

        jTextArea2.setColumns(20);
        jTextArea2.setRows(5);
        jScrollPane3.setViewportView(jTextArea2);

        jSplitPane2.setLeftComponent(jScrollPane3);

        jButton1.setText("Post Tweet");
        jSplitPane2.setRightComponent(jButton1);

        jList2.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        jList2.setToolTipText("News Feed");
        jScrollPane4.setViewportView(jList2);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(76, 76, 76)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jSplitPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                    .addComponent(jScrollPane2)
                    .addComponent(jScrollPane4)
                    .addComponent(jSplitPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 275, Short.MAX_VALUE))
                .addContainerGap(179, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jSplitPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jSplitPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(72, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
   
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JList<String> jList1;
    private javax.swing.JList<String> jList2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JSplitPane jSplitPane1;
    private javax.swing.JSplitPane jSplitPane2;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JTextArea jTextArea2;
    private TreeView treeView;
    private DefaultListModel<String> followingListModel;
    private DefaultListModel<String> newsFeedListModel;
    // End of variables declaration//GEN-END:variables
}
